language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install codecov
  - pip install pytest-cov
script:
  - pytest --cov-report=xml --cov=deeptabular tests/
after_success:
  - codecov